language: python

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=pyflakes
    - python: pypy
      env: TOX_ENV=test-pypy
    - python: 2.7
      env: TOX_ENV=test-py27-codecov-travis
    - python: 3.6
      env: TOX_ENV=test-py36-codecov-travis
    - python: 3.7
      env: TOX_ENV=test-py37
    - python: 3.8
      env: TOX_ENV=test-py38
    - python: 3.8
      env: TOX_ENV=twisted-apidoc

  allow_failures:
    # Twisted trunk is broken for now.
    - env: TOX_ENV=twisted-apidoc

install:
    - pip install tox

script: tox -e $TOX_ENV

notifications:
    email: false

# Do an automatic PyPi release when a tag is created.
# http://docs.travis-ci.com/user/deployment/pypi/
# Make sure builds are triggered for any push so that the tag push will also
# trigger a build.
deploy:
  provider: pypi
  # twistedchecker-robot is associated with adi.roiban email address from
  # Gmail. It uses a random password which was not recorded in plain text.
  user: twistedchecker-robot
  password:
    secure: D8Jlbsm8sN1Nz11SgFI7HRxjx0/gLDl66RB101nrhP4Bs4tzK2s9duu7P6nGRIupX5r5czRpSyhPrPQjci3UhcxZf5OTTCd5pamGBd7dv32Usr2aXWhvIfulX+i7jtbOBiWQT7JhxjSjlvyZLW0kka3eClQaD+D4iI64zaBn7y0=
  on:
    tags: true
    # All branches is still required.
    # https://github.com/travis-ci/travis-ci/issues/1675
    all_branches: true
    condition: "$TOX_ENV = test-py27-codecov-travis"
